// <auto-generated />
namespace XYZ.Agendamentos.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ProjetoDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProjetoDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202002080248499_ProjetoDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
